server:
  port: 4060

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123qwe
    url: jdbc:mysql://106.12.203.3:3306/atomic?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  elasticjob:
    zookeeper:
      server-lists: 106.12.203.43:2181
      namespace: atomic-daemon
